### ISSUE TITLE
HTMLDocumentation task crashes from temp-file not found

### ISSUE THREAD

**Issue by PeterJudgeZA** [Riverside-Software/pct#108]
HTMLDocumentation task fails for me with the errors below.
I am confused by the CLR reference (since my code does not contain any)

DLC is 11.5+
using PCT-194.jar and openedge_services.jar from 11.3

```
[HTMLDocumentation] Unhandled Exception: System.Runtime.InteropServices.SEHException: External component has thrown an exception.
[HTMLDocumentation]    at _CxxThrowException(Void* , _s__ThrowInfo* )
[HTMLDocumentation]    at Progress.ClrBridge.BrgTypeInspector.Inspect(BrgTypeInspector* , SByte* )
[HTMLDocumentation] Result: -1073741819
```

followed by

```
Caused by: java.io.FileNotFoundException: C:\Users\pjudge\AppData\Local\Temp\PCTResult41058.out (The system cannot find the file specified)
    at java.io.FileInputStream.open(Native Method)
```

**Comment by jakejustus** [comment]
The temp file error is caused because PCT is not able to read the result of the procedure (yes, I have to rely on files because _progres can't send a return code :-) )
Could you have a look at the target directory ? It should contain a list of html files already processed. If possible, could you attach the XML file which should be processed after the last one ? They're processed by alphabetical order.

**Comment by PeterJudgeZA** [comment]
The file is attached.

I'm trying to build HTML and XML doc for the code in https://github.com/PeterJudge-PSC/InjectABL

**Comment by jakejustus** [comment]
I will try to execute your build file

**Comment by PeterJudgeZA** [comment]
Use these instead.

That project needs some cleanup (part of what I'm trying to do :)

**Comment by jakejustus** [comment]
Use what ?

**Comment by jakejustus** [comment]
Just cloned InjectABL : https://github.com/jakejustus/InjectABL
In order to create a sample build file and reproduced the problem. Then I found your build.xml in resources directory :-(
By the way, this comes from OpenEdge.InjectABL.Lifecycle.IPipeline.xml when it is processed by HtmlDocumentation task. XML file has been submitted to Mike for analysis.

**Comment by jakejustus** [comment]
Hi Peter,

Did you try to submit the protrace file to your colleagues ?

**Comment by gquerret** [comment]
Not reproduced
