### ISSUE TITLE
Table CRC is not enough to know if a file has to be recompiled

### ISSUE THREAD

**Issue by jakejustus** [Riverside-Software/pct#128]
Long-standing issue (since PSC changed CRC rules) ; adding a new index doesn't change the CRC of the table anymore, meaning that it's not caught by PCT, and programs referencing this table may not be recompiled and then use this index.
Another way of storing table signature should be added in the .crc files

**Comment by axelebnerpcsat** [comment]
How about to add each _index._idx-CRC to the table-CRC or create a own index-CRC table

**Comment by laumingis** [comment]
R-codes should probably also be recompiled if triggers are modified for the table. It does not change crc, but without recompilation old r-codes will not pick up changes.

This influences not only triggers, but other changes, listed under **Which schema changes do NOT REQUIRE recompiling but may affect the code** in http://knowledgebase.progress.com/articles/Article/P167155 as well.

**Comment by stefandrissen** [comment]
Additionally when a field is renamed, the table crc also does not change (which the prokb above confirms). 

For extra fun
- the old 11.7 r-code works fine when executed but the old 12.0 r-code fails with crc errors when executed (using pct-210-master)
- the old 11.7 oracle r-code also fails when executed - probably due to the position being changed as a result of fields being positioned alphabetically by the progress to oracle migration utility

**Comment by gquerret** [comment]
Won't be fixed in PCT.
