### ISSUE TITLE
PCTCompile failing sporadically

### ISSUE THREAD

**Issue by mebrighton** [Riverside-Software/pct#176]
Hi 
Our PCTCompile statement is failing sometimes but successful at other times.
After a failure, rerunning the Ant Job can result in success. 
Sometimes it takes a few retries for the job to succeed.
Jenkins verbose console output attached.
Failure snippet from the attached verbose Jenkins log:

```
PctCompile(C:\Jenkins\jobs\Dev_Build_SOA\workspace\server|SOAP\Services\Manifest\AmendDomestic.p|) : 0/1/0
    at com.phenix.pct.PCTBgCompile$CompilationBackgroundWorker.handleResponse(PCTBgCompile.java:297)
    at com.phenix.pct.BackgroundWorker.listen(BackgroundWorker.java:126)
    at com.phenix.pct.PCTBgRun$ListenerThread$1.run(PCTBgRun.java:679)
    at java.lang.Thread.run(Thread.java:745) 
```

[JenkinsConsoleOutput.txt](https://github.com/Riverside-Software/pct/files/500815/JenkinsConsoleOutput.txt)

**Comment by gquerret** [comment]
It's not clear in the documentation (since PCTCompile and PCTCompiled were merged) that multiple threads shouldn't be used when compiling classes. Each session doesn't know about compilation of parent classes, and it's a common behavior to see this kind of random failure with classes. Please re-open if you see the same issue with a single thread.

**Comment by mebrighton** [comment]
Ok thanks
