### ISSUE TITLE
PCTCompile doesn't report some warnings

### ISSUE THREAD

**Issue by Hanna19** [Riverside-Software/pct#207]
Hi,
I use PCT-207.jar.
PCTCompile writes warnings (type 2) to the PCTDir/CompiledFile.p.warnings.
There are 2 issues which I found:
1 - It doesn't do it for all warnings. For example the warning 4027 is not reported.  (please more info below)
2 - CompiledFile.p.warnigns file won't be deleted even if the CompiledFile was corrected.

Ideally, I think,  the warnings should be reported the same way as errors - not in the warnings files.
It should be a mechanism to suspend reporting of some warnings by PCTCompile parameter(s).  
Probably for consistency, the best would be to follow the logic of Progress startup parameters -swl and  -noincrwarn.  

Details for point 1:
PCTCompile reports following warnings in our application (thousands of programs): 
1- ** WARNING--TRANSACTION keyword given within actual transaction level. (214)
2- WARNING: Executable statement (....) will not be reached. (15090)
3- -mmax exceeded. Automatically increasing from 3096 to 6408. (5409)

PCTCompile doesn't report :
**Warning: Cannot fit FILL-IN (..) within frame f1. (4027)

Regards
Hanna Boguslawska

**Comment by gquerret** [comment]
* Warnings not being reported: do you use xmlXref ? If so, that's an OpenEdge issue, which should be fixed in 11.7.

* .warnings files not being deleted: that's an issue, it will be fixed

The best way to know about warnings is to use the [OpenEdge plugin for SonarQube](https://github.com/Riverside-Software/sonar-openedge), as it will report all new warnings in the SQ dashboard.

**Comment by gquerret** [comment]
Fix for the .warnings file has been pushed in master
