### ISSUE TITLE
pct:compile - stopping Ant should stop AVM

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Riverside-Software/pct#78]
What steps will reproduce the problem?

1. have a build job that will take some time (1 hour in my case)
2. see errors flowing in to the Ant console (since I'm in the setup phase)
3. stop the Ant build 

What is the expected output? What do you see instead?

The Ant build stops fine, but the _progres.exe that was launched for the pct:compile task keeps running until it has finished. 

If the task is connected to databases in single user mode then subsequent builds fail until the task is killed.

Work-around: kill the task

What version of the product are you using? On what operating system?

- Windows 7 x64
- Architect 10.2B (Eclipse 3.4.2)
- Ant 1.7.0 (supplied by JDT of Eclipse 3.4.2)
- PCT-192
- JDK 1.8.0_25

Please provide any additional information below.

```
Original issue reported on code.google.com by `stefan.d...@gmail.com` on 24 Nov 2014 at 8:09
```

**Comment by stefandrissen** [comment]
Since Progress OpenEdge 12.6, PDSOE is a lot better at killing what it started. A stop in the console will now also kill Ant, resolving this issue.

Hopefully this will not be broken when [OCTA-51843](https://community.progress.com/s/article/When-closing-PDSOE-any-app-that-was-started-from-PDSOE-will-be-shut-down-in-version-12-6) is fixed.
